
import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
    <html lang="en">
      <body className={``}>
        <main className="min-h-screen">
          <Header />

        {children}
        <Toaster richColors />
        </main>
        
        {/* Footer */}
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>Made with ❤️ by akshat lambhate</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
